services:
  - type: web
    name: telegram-youtube-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: PORT
        value: 8080 
